services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"